// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare module 'CommunicationProtocol'
{

    export enum RequestCode
    {
        Handshake = "Handshake",
        Login = "Login",
        Register = "Register",
    }
    export enum ResponseCode
    {
        Success = "Success",
        InvalidProtocol = "InvalidProtocol",
        InvalidLogin = "InvalidLogin",
        InvalidPassword = "InvalidPassword",
    }
    export interface Header
    {
        PayloadSize?: number;
    }

    export interface Response
    {
        Header?: Header;
        RequestCode?: RequestCode;
        ResponseCode?: ResponseCode;
        ErrorMessage?: string;
        Payload?: Uint8Array;
    }

    export interface Request
    {
        Header?: Header;
        RequestCode?: RequestCode;
        Payload?: Uint8Array;
    }

    export interface HandshakePayload
    {
        ProtocolVersion?: number;
    }

}

